version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pwd
      - ls -l
      - mkdir dependencias
      - ls -l
  pre_build:
    commands:
      - echo "Pre Build"
  build:
    commands:
      - echo "Build"
  post_build:
    commands:
      - echo "Post Build"

