version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando herramientas necesarias..."
      - apt-get update && apt-get install -y zip
      - echo "El directorio actual es $CODEBUILD_SRC_DIR"

  pre_build:
    commands:
      - echo "Generando Zip con proyecto"
      - zip -r kanri_app_code.zip ./kanri_app
      - echo "Cargando proyecto a S3"
      - aws s3 cp ./kanri_app_code.zip s3://kanri-project-files/kanri_code/kanri_app_code.zip
      - aws lambda update-function-code --function-name "kanri_lambda" --s3-bucket kanri-project-files --s3-key kanri_code/kanri_app_code.zip

  build:
    commands:
      - echo "build process"
      - echo "Actualizar Lambda $LAYER_UPDATE"
      - if [ "$LAYER_UPDATE" = "true" ]; then
          echo "Actualizando layer...";
          LAYER_VERSION_ARN=$(aws lambda publish-layer-version --layer-name "kanri_layer" --description "Layer para el proyecto Kanri" --content S3Bucket=kanri-project-files,S3Key=layer_zip/kanri_layer.zip --compatible-runtimes python3.11 --query 'LayerVersionArn' --output text);
          echo "Layer ARN $LAYER_VERSION_ARN";
        fi
      - echo "Cargabdo lambda"
      - sleep 5
      - NEW_VERSION=$(aws lambda publish-version --function-name "kanri_lambda" --query 'Version' --output text)
      - echo "Nueva versión de Lambda publicada $NEW_VERSION"
      - |
        if [ ! -z "$LAYER_VERSION_ARN" ]; then
          echo "Asociando layer a la función Lambda...";
          aws lambda update-function-configuration --function-name "kanri_lambda" --layers $LAYER_VERSION_ARN;
        fi
      - |
        if [ ! -z "$NEW_VERSION" ]; then
          echo "Actualizando alias...";
          aws lambda update-alias --function-name "kanri_lambda" --name "$ALIAS_NAME" --function-version "$NEW_VERSION";
          echo "Alias $ALIAS_NAME actualizado para apuntar a la versión $NEW_VERSION";
        fi


  post_build:
    commands:
      - rm $CODEBUILD_SRC_DIR/kanri_app_code.zip

artifacts:
  files:
    #- function.zip
    #- kanri_layer.zip
